plex:
  image:
    repository: ghcr.io/k8s-at-home/plex
  env:
    # -- Set the container timezone
    TZ: Europe/Berlin
  ingress:
    main:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
       # kubernetes.io/ingress.class: nginx
      hosts:
        - host: &host plex.anneken.cloud
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: plex-tls-certificate
          hosts:
            - *host