# network-attachment-definition.yaml
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-iot
  namespace: default
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "type": "ipvlan",
      "master": "enp6s18",
      "ipam": {
        "type": "static",
        "routes": [
          { "dst": "10.10.0.0/24", "gw": "10.10.0.1" }
        ]
      }
    }
