app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.io/vaultwarden/server
            tag: 1.30.5-alpine
          env:
          - name: ADMIN_TOKEN
            valueFrom:
              secretKeyRef:
                name: vaultwarden-admin-token
                key: password
  service:
    main:
      ports:
        http:
          port: 80
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host password.anneken.cloud
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: vaultwarden-tls-certificate
  persistence:
    data:
      accessMode: ReadWriteOnce
      size: 1Gi
      globalMounts:
        - path: /data
          readOnly: false