all:
  vars:
    control_plane_endpoint: 10.10.0.210
    load_balancer_ip_pool:
      - 10.10.0.224/28
metal:
  children:
    masters:
      hosts:
        k8s-prod-master01: {ansible_host: 10.10.0.11, mac: 'bc:24:11:a5:6f:23', disk: sda, network_interface: eth0}
        k8s-prod-master02: {ansible_host: 10.10.0.12, mac: 'bc:24:11:f2:7a:6b', disk: sda, network_interface: eth0}
        k8s-prod-master03: {ansible_host: 10.10.0.13, mac: 'bc:24:11:0d:d1:12', disk: sda, network_interface: eth0}
    workers:
      hosts: {
        k8s-prod-worker01: {ansible_host: 10.10.0.21, mac: 'bc:24:11:c0:a2:01', disk: sda, network_interface: eth0}
        k8s-prod-worker02: {ansible_host: 10.10.0.22, mac: 'bc:24:11:40:5d:f1', disk: sda, network_interface: eth0}
        k8s-prod-worker03: {ansible_host: 10.10.0.22, mac: 'bc:24:11:82:18:3a', disk: sda, network_interface: eth0}
      }
       # metal3: {ansible_host: 192.168.178.13, mac: 'bc:24:11:33:42:b3', disk: sda, network_interface: eth0}
