all:
  vars:
    control_plane_endpoint: 192.168.178.5
    load_balancer_ip_pool:
      - 192.168.178.224/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.178.10, mac: 'bc:24:11:64:44:9d', disk: sda, network_interface: eth0}
        metal1: {ansible_host: 192.168.178.11, mac: 'bc:24:11:50:14:3e', disk: sda, network_interface: eth0}
        metal2: {ansible_host: 192.168.178.12, mac: 'bc:24:11:45:a1:be', disk: sda, network_interface: eth0}
    workers:
      hosts {}
       # metal3: {ansible_host: 192.168.178.13, mac: 'bc:24:11:33:42:b3', disk: sda, network_interface: eth0}
