app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/koenkk/zigbee2mqtt
            tag: 1.39.0
          env:
            ZIGBEE2MQTT_DATA: /data
            ZIGBEE2MQTT_CONFIG_HOMEASSISTANT: "true"
            ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_RETAIN: "true"
            ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: "false"
            ZIGBEE2MQTT_CONFIG_SERIAL_PORT: tcp://192.168.178.111:6638
            ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC: zigbee2mqtt
            ZIGBEE2MQTT_CONFIG_MQTT_INCLUDE_DEVICE_INFORMATION: "true"
            ZIGBEE2MQTT_CONFIG_MQTT_KEEPALIVE: 60
            ZIGBEE2MQTT_CONFIG_MQTT_REJECT_UNAUTHORIZED: "true"
            ZIGBEE2MQTT_CONFIG_MQTT_SERVER: "mqtt://emqx-listeners"
            ZIGBEE2MQTT_CONFIG_MQTT_VERSION: 5
            ZIGBEE2MQTT_CONFIG_MQTT_USER: "${SECRET_MQTT_USERNAME}"
            ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: "${SECRET_MQTT_PASSWORD}"
            ZIGBEE2MQTT_CONFIG_EXPERIMENTAL_NEW_API: "true"
            ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: 8080
            ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL: warn
            ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_OUTPUT: '["console"]'
            ZIGBEE2MQTT_CONFIG_ADVANCED_CHANNEL: 25
            ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: 6755
            ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: "[221, 221, 221, 221, 221, 221, 221, 221]"
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true
              spec:
                failureThreshold: 30
                periodSeconds: 5
          resources:
            requests:
              memory: 128M
              cpu: 20m
            limits:
              memory: 256M

  service:
      app:
        controller: zigbee2mqtt
        ports:
          http:
            port: 8080
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host zigbee.anneken.cloud
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: zigbee2mqtt-tls-certificate
  #persistence:
  #  data:
  #    accessMode: ReadWriteOnce
  #    size: 10Gi
  #    advancedMounts:
  #      main:
  #        main:
  #          - path: /usr/src/paperless/data
  #            subPath: data
  #          - path: /usr/src/paperless/media
  #            subPath: media
