elementweb:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: "homelab-tunnel.anneken.cloud"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    hosts:
      - host: &frontend_host chat.anneken.cloud
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: element-tls-certificate
        hosts:
          - *frontend_host
  config:
    default:
      base_url: https://matrix.anneken.cloud
      server_name: anneken.cloud

dendrite:
  dendrite_config:
    global:
      server_name: matrix.anneken.cloud
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hostName: matrix.anneken.cloud
    tls:
      - hosts:
          - matrix.anneken.cloud
        secretName: matrix-tls-certificate
  postgresql:
    enabled: true
